version: '3'

services:
  dev:
    tty: true
    image: node:10
    volumes:
      - .:/usr/src/service
      - nodemodules:/usr/src/service/node_modules
    environment:
      - NODE_ENV=development
    working_dir: /usr/src/service
    command: npm run dev
    ports: 
      - 1234:1234
      - 1235:1235

volumes:
  nodemodules:
    external: true